const SYSTEM = "cargo";
const APPROVAL_SYSTEM = "approval";
const APPROVE_APPLICATION_KIND = "APPROVE APPLICATION";
const APPROVE_CONTRACT_KIND = "APPROVE CONTRACT";
const APPROVE_CHANGE_REQUEST_KIND = "APPROVE UPDATE REQUEST";
const APPROVE_CANCEL_REQUEST_KIND = "APPROVE CANCEL REQUEST";
const APPROVE_HOLDER_KIND = "APPROVE HOLDER";

const PREPARED = "Подготовлен";
const UNDER_REVISION = "На доработке";
const APPLIED = "Действует";
const CANCELLED = "Расторгнут";
const UNCOMPLETED = "Не состоялся";
const NOT_ACTIVE = "В архиве";

const MULTI_EXCEL = "Реестр";
const SOLO_EXCEL = "Единичный";

const CONTRACT_PRINT_TYPE = "Полис";
const NOTIFICATION_PRINT_TYPE = "Уведомелние";
const APPLICATION_PRINT_TYPE = "Акцептованное заявление";

const PROCESSING = "Обрабатывается";
const ACCEPTED = "Принято";
const REJECTED = "Отклонено";

const PROCESSING_TYPE = "PROCESSING";
const ACCEPTED_TYPE = "ACCEPTED";
const REJECTED_TYPE = "REJECTED";

const REQUEST_CHANGE_KIND = "change";
const REQUEST_CANCEL_KIND = "cancel";

const APPLICATION_ROUTE_NAME = "Application";
const STATISTICS_ROUTE_NAME = "Statistics";
const APPLICATION_DETAIL_ROUTE_NAME = "ApplicationDetail";
const CONTRACT_ROUTE_NAME = "Contract";
const CONTRACT_CREATE_ROUTE_NAME = "ContractCreate";
const CONTRACT_CREATE_FROM_EXCEL_ROUTE_NAME = "ContractCreateFromExcel";
const REGISTRIES = "Registries";
const CHANGE_REQUEST_FROM_EXCEL_ROUTE_NAME = "ChangeRequestFromExcel";
const CONTRACT_DETAIL_ROUTE_NAME = "ContractDetail";
const APPLICATION_REQUEST_TO_CHANGE_ROUTE_NAME = "ApplicationRequestToChange";
const APPLICATION_REQUEST_TO_CANCEL_ROUTE_NAME = "ApplicationRequestToCancel";
const CARGO_APP_ROUTE_NAME = "CargoApp";
const HOLDER_DETAIL_ROUTE_NAME = "HolderDetail";
const HOLDER_ROUTE_NAME = "Holder";
const DICTIONARY_ROUTE_NAME = "Dictionary";
const HOLDER_MANAGERS_ROUTE_NAME = "HolderManager";
const BASICS_ROUTE_NAME = "Basics";
const POWER_OF_ATTORNEY_ROUTE_NAME = "PowerOfAttorney";
const POWER_OF_ATTORNEY_CREATE_ROUTE_NAME = "PowerOfAttorneyCreate";
const ERROR_ROUTE_NAME = "Error";
const NOT_FOUND_ROUTE_NAME = "NotFound";
const NO_ACCESS_ROUTE_NAME = "NoAccess";
const UNEXPECTED_ROUTE_NAME = "UnexpectedError";
const EXTERNAL_CONTRACT = "EXTERNAL_CONTRACT";
const MONEY_PATH = "/money";
const GENERAL_AGREEMENT_ROUTE_NAME = "GeneralAgreement";
const GENERAL_AGREEMENT_CREATE_ROUTE_NAME = "GeneralAgreementCreate";
const GENERAL_AGREEMENT_DETAIL_ROUTE_NAME = "GeneralAgreementDetail";
const ADDITIONAL_AGREEMENT_ROUTE_NAME = "additionalAgreement";
const ADDITIONAL_AGREEMENT_CREATE_ROUTE_NAME = "AdditionalAgreementCreate"
const ADDITIONAL_AGREEMENT_DETAIL_ROUTE_NAME = "AdditionalAgreementDetail"
const AGREEMENT_ROUTE_NAME = "Agreement";
const AGREEMENT_CREATE_ROUTE_NAME = "AgreementCreate";
const AGREEMENT_DETAIL_ROUTE_NAME = "AgreementDetail";
const AGREEMENT_VERSION_CREATE_ROUTE_NAME = "AgreementVersionCreate";
const AGREEMENT_VERSION_DETAIL_ROUTE_NAME = "AgreementVersionDetail";

const CARGO_32_KIND_OF_INSURANCE = "07";
const LIABILITY_KIND_OF_INSURANCE = "32";

const APPROVAL_STATUS_REFUSE = "REFUSE";
const APPROVAL_STATUS_REFUSE_FINAL = "REFUSE_FINAL";
const APPROVAL_STATUS_IN_PROCESS = "IN_PROCESS";
const APPROVAL_STATUS_APPROVED = "APPROVED";

const APPLICATION_REQUEST_TYPE = "Application";
const CHANGE_REQUEST_TYPE = "ChangeRequest";
const CANCEL_REQUEST_TYPE = "CancelRequest";

const CARGO_TERMS = "CargoTerms";
const IN_TIME_LIABILITY_TERMS = "InTimeLiabilityTerms";

const AGAINST_ALL_RISKS = "AgainstAllRisks";
const NAMED_PERILS_INSURANCE_RISKS = "NamedPerilsInsurance";

const ABSOLUTE_DEDUCTIBLE_KIND = "AbsoluteDeductible";
const PERCENT_DEDUCTIBLE_KIND = "PercentDeductible";

const CARGO_PRODUCT_CODE = "CARGO";
const IN_TIME_PRODUCT_CODE = "IN_TIME";

const CONTRACT = "CONTRACT";
const GENERAL_AGREEMENT = "GENERAL AGREEMENT";

const TERMS_MANIPULATE = "TermsManipulate";
const STATUS_CHANGE = "StatusChange";

const LIABILITY_PATH = "/liability/";
const VALIDATOR_PATH = "/validator/";
const ISSUE_STRATEGY_PATH = "/issueStrategies/";
const LIMITATION_PATH = "/limitation/";
const DICTIONARY_PATH = "/dictionary/";
const ENUM_PATH = "/enum/";

const NOT_FOUND_CODE = "notFound";

const PARTY_HOLDER_ROLE = "holder";
const PARTY_BENEFICIARY_ROLE = "beneficiary";
const PARTY_THIRD_ROLE = "third party";

const ERROR_ALERT_TYPE = "error";
const WARNING_ALERT_TYPE = "warning";
const SUCCESS_ALERT_TYPE = "success";

const SEARCH_BY_HOLDER = 'SEARCH_BY_HOLDER'
const SEARCH_BY_DATE = 'SEARCH_BY_DATE'
const SEARCH_BY_NUMBER = 'SEARCH_BY_NUMBER'
const SEARCH_BY_KIND = 'SEARCH_BY_KIND'



let alert_types = {
    SUCCESS: SUCCESS_ALERT_TYPE,
    WARNING: WARNING_ALERT_TYPE,
    ERROR: ERROR_ALERT_TYPE
};

let kinds_of_insurance = {
    CARGO_32: CARGO_32_KIND_OF_INSURANCE,
    LIABILITY: LIABILITY_KIND_OF_INSURANCE,
    "15": "Страхование ответственности перевозчиков [15]",
    "32": "Страхование ответственности экспедиторов [32]",
    "112": "Страхование грузов [112]",
    "07": "Страхование грузов [07]",
    "0701": "Страхование имущества [0701]",
};

let approval_statuses = {
    IN_PROCESS: APPROVAL_STATUS_IN_PROCESS,
    APPROVED: APPROVAL_STATUS_APPROVED,
    REFUSE: APPROVAL_STATUS_REFUSE,
    REFUSE_FINAL: APPROVAL_STATUS_REFUSE_FINAL
};

let deductible_kinds = {
    ABSOLUTE: ABSOLUTE_DEDUCTIBLE_KIND,
    PERCENT: PERCENT_DEDUCTIBLE_KIND
};

let risk_types = {
    AGAINST_ALL: AGAINST_ALL_RISKS,
    NAMED_PERILS_INSURANCE: NAMED_PERILS_INSURANCE_RISKS
};

let error_codes = {
    NOT_FOUND: NOT_FOUND_CODE,
};

let service_path = {
    LIABILITY: LIABILITY_PATH,
    VALIDATOR: VALIDATOR_PATH,
    ISSUE_STRATEGY: ISSUE_STRATEGY_PATH,
    DICTIONARY: DICTIONARY_PATH,
    ENUM: ENUM_PATH,
    LIMITATION: LIMITATION_PATH
};

let history_types = {
    TERMS_MANIPULATE: TERMS_MANIPULATE,
    STATUS_CHANGE: STATUS_CHANGE,
};

let request_types = {
    APPLICATION: APPLICATION_REQUEST_TYPE,
    CHANGE_REQUEST: CHANGE_REQUEST_TYPE,
    CANCEL_REQUEST: CANCEL_REQUEST_TYPE
};

let terms_types = {
    CARGO: CARGO_TERMS,
    IN_TIME_LIABILITY: IN_TIME_LIABILITY_TERMS,
};

let product_codes = {
    CARGO: CARGO_PRODUCT_CODE,
    IN_TIME: IN_TIME_PRODUCT_CODE,
};

let route_names = {
    HOLDER: HOLDER_ROUTE_NAME,
    HOLDER_DETAIL: HOLDER_DETAIL_ROUTE_NAME,
    CARGO_APP: CARGO_APP_ROUTE_NAME,
    DICTIONARY: DICTIONARY_ROUTE_NAME,
    HOLDER_MANAGERS: HOLDER_MANAGERS_ROUTE_NAME,
    BASICS: BASICS_ROUTE_NAME,
    POWER_OF_ATTORNEY: POWER_OF_ATTORNEY_ROUTE_NAME,
    POWER_OF_ATTORNEY_CREATE: POWER_OF_ATTORNEY_CREATE_ROUTE_NAME,
    APPLICATION: APPLICATION_ROUTE_NAME,
    STATISTICS: STATISTICS_ROUTE_NAME,
    GENERAL_AGREEMENT: GENERAL_AGREEMENT_ROUTE_NAME,
    GENERAL_AGREEMENT_CREATE: GENERAL_AGREEMENT_CREATE_ROUTE_NAME,
    GENERAL_AGREEMENT_DETAIL: GENERAL_AGREEMENT_DETAIL_ROUTE_NAME,
    ADDITIONAL_AGREEMENT: ADDITIONAL_AGREEMENT_ROUTE_NAME,
    ADDITIONAL_AGREEMENT_DETAIL: ADDITIONAL_AGREEMENT_DETAIL_ROUTE_NAME,
    ADDITIONAL_AGREEMENT_CREATE: ADDITIONAL_AGREEMENT_CREATE_ROUTE_NAME,
    AGREEMENT: AGREEMENT_ROUTE_NAME,
    AGREEMENT_CREATE: AGREEMENT_CREATE_ROUTE_NAME,
    AGREEMENT_DETAIL: AGREEMENT_DETAIL_ROUTE_NAME,
    AGREEMENT_VERSION_CREATE: AGREEMENT_VERSION_CREATE_ROUTE_NAME,
    AGREEMENT_VERSION_DETAIL: AGREEMENT_VERSION_DETAIL_ROUTE_NAME,
    APPLICATION_DETAIL: APPLICATION_DETAIL_ROUTE_NAME,
    CONTRACT: CONTRACT_ROUTE_NAME,
    CONTRACT_CREATE: CONTRACT_CREATE_ROUTE_NAME,
    CONTRACT_CREATE_FROM_EXCEL: CONTRACT_CREATE_FROM_EXCEL_ROUTE_NAME,
    REGISTRIES: REGISTRIES,
    CHANGE_REQUEST_FROM_EXCEL: CHANGE_REQUEST_FROM_EXCEL_ROUTE_NAME,
    CONTRACT_DETAIL: CONTRACT_DETAIL_ROUTE_NAME,
    APPLICATION_REQUEST_TO_CHANGE: APPLICATION_REQUEST_TO_CHANGE_ROUTE_NAME,
    APPLICATION_REQUEST_TO_CANCEL: APPLICATION_REQUEST_TO_CANCEL_ROUTE_NAME,
    ERROR: ERROR_ROUTE_NAME,
    NOT_FOUND: NOT_FOUND_ROUTE_NAME,
    NO_ACCESS: NO_ACCESS_ROUTE_NAME,
    UNEXPECTED: UNEXPECTED_ROUTE_NAME
};

let excelTypes = {
    MULTI_EXCEL: MULTI_EXCEL,
    SOLO_EXCEL: SOLO_EXCEL
};

let printTypes = {
    CONTRACT: CONTRACT_PRINT_TYPE,
    NOTIFICATION: NOTIFICATION_PRINT_TYPE,
    APPLICATION: APPLICATION_PRINT_TYPE
};

let statuses = {
    PREPARED: PREPARED,
    UNDER_REVISION: UNDER_REVISION,
    APPLIED: APPLIED,
    CANCELLED: CANCELLED,
    UNCOMPLETED: UNCOMPLETED,
    PROCESSING: PROCESSING,
    ACCEPTED: ACCEPTED,
    REJECTED: REJECTED,
    NOT_ACTIVE: NOT_ACTIVE
};

let status_types = {
    PROCESSING: PROCESSING_TYPE,
    ACCEPTED: ACCEPTED_TYPE,
    REJECTED: REJECTED_TYPE,
};

let approve_kinds = {
    APPLICATION: APPROVE_APPLICATION_KIND,
    CONTRACT: APPROVE_CONTRACT_KIND,
    CHANGE_REQUEST: APPROVE_CHANGE_REQUEST_KIND,
    CANCEL_REQUEST: APPROVE_CANCEL_REQUEST_KIND,
    APPROVE_HOLDER: APPROVE_HOLDER_KIND
};

let request_kinds = {
    CHANGE: REQUEST_CHANGE_KIND,
    CANCEL: REQUEST_CANCEL_KIND,
};

let common_consts = {
    SYSTEM: SYSTEM,
    APPROVAL_SYSTEM: APPROVAL_SYSTEM
};

let party_roles = {
    HOLDER: PARTY_HOLDER_ROLE,
    BENEFICIARY: PARTY_BENEFICIARY_ROLE,
    THIRD_PARTY: PARTY_THIRD_ROLE
};

let redirect = {
    TYPE: EXTERNAL_CONTRACT,
    PATH: MONEY_PATH,
    CONTRACT: CONTRACT,
    GENERAL_AGREEMENT: GENERAL_AGREEMENT
};

let search_names = {
    holder: SEARCH_BY_HOLDER,
    number: SEARCH_BY_NUMBER,
    date: SEARCH_BY_DATE,
    kind: SEARCH_BY_KIND,
}


export {
    route_names,
    excelTypes,
    printTypes,
    statuses,
    status_types,
    approve_kinds,
    request_kinds,
    common_consts,
    redirect,
    request_types,
    terms_types,
    product_codes,
    history_types,
    service_path,
    error_codes,
    alert_types,
    risk_types,
    deductible_kinds,
    approval_statuses,
    party_roles,
    kinds_of_insurance,
    search_names
}